# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vincent Billey
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Vincent Billey aka Fenn's blog. The opinions in this blog are my own and do not represent
  anyone else's.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vincent.billey.me" # the base hostname & protocol for your site
twitter_username: Fenntasy
github_username:  Fenntasy

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

# Outputting
permalink: /:title/
exclude:
  - s3_website.yml
  - publish
  - Gemfile
  - Gemfile.lock
